[package]
name = "godot"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "2d", "3d"] # possibly: "ffi"
categories = ["game-engines", "graphics"]

[features]
default = ["codegen-full"]
custom-godot = ["godot-core/custom-godot"]
double-precision = ["godot-core/double-precision"]
formatted = ["godot-core/codegen-fmt"]
serde = ["godot-core/serde"]
lazy-function-tables = ["godot-core/codegen-lazy-fptrs"]
experimental-threads = ["godot-core/experimental-threads"]
experimental-godot-api = ["godot-core/experimental-godot-api"]

# Private features, they are under no stability guarantee
codegen-full = ["godot-core/codegen-full"]
trace = ["godot-core/trace"]

[dependencies]
godot-core = { path = "../godot-core" }
godot-macros = { path = "../godot-macros" }
