[package]
name = "godot-macros"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "derive", "macro"]
categories = ["game-engines", "graphics"]

[features]
custom-godot = ["godot-bindings/custom-godot"]

[lib]
proc-macro = true

# Reverse dev dependencies so doctests can use `godot::` prefix
[dev-dependencies]
godot = { path = "../godot" }

[dependencies]
# Minimum versions compatible with -Zminimal-versions
proc-macro2 = "1.0.63"
quote = "1.0.29"

venial = "0.5"

[build-dependencies]
godot-bindings = { path = "../godot-bindings" } # emit_godot_version_cfg
